1722075830.848046 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:98 __init__ INFO: Starting DataFlowKernel with config
Config(
    app_cache=True, 
    checkpoint_files=None, 
    checkpoint_mode=None, 
    checkpoint_period=None, 
    dependency_resolver=None, 
    executors=(ThreadPoolExecutor(
        label='threads', 
        max_threads=2, 
        storage_access=None, 
        thread_name_prefix='', 
        working_dir=None
    ),), 
    exit_mode='cleanup', 
    garbage_collect=True, 
    initialize_logging=True, 
    internal_tasks_max_threads=10, 
    max_idletime=120.0, 
    monitoring=None, 
    retries=0, 
    retry_handler=None, 
    run_dir='runinfo', 
    std_autopath=None, 
    strategy='simple', 
    strategy_period=5, 
    usage_tracking=0
)
1722075830.848240 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:100 __init__ INFO: Parsl version: 2024.07.22
1722075830.848347 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.usage_tracking.usage:118 __init__ DEBUG: Tracking level: 0
1722075830.848472 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:128 __init__ INFO: Run id is: 69fd9839-78e9-4adc-99e6-d72b2ad4e34f
1722075830.916907 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:135 __init__ DEBUG: Considering candidate for workflow name: /home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py
1722075830.917053 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:135 __init__ DEBUG: Considering candidate for workflow name: /home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py
1722075830.917131 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:135 __init__ DEBUG: Considering candidate for workflow name: /home/ubuntu/data/test/parsl_pro/parsl_script.py
1722075830.917194 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:141 __init__ DEBUG: Using parsl_script.py as workflow name
1722075830.917371 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.memoization:163 __init__ INFO: App caching initialized
1722075830.917442 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.jobs.strategy:145 __init__ DEBUG: Scaling strategy: simple
1722075830.920907 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1016 submit DEBUG: Task 0 will be sent to executor threads
1722075830.921045 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:818 _add_output_deps DEBUG: Adding output dependencies
1722075830.921103 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1067 submit DEBUG: Added output dependencies
1722075830.921153 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1080 submit DEBUG: Gathering dependencies
1722075830.921200 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1083 submit DEBUG: Gathered dependencies
1722075830.921247 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1098 submit INFO: Task 0 submitted for App install_cunumeric, not waiting on any dependency
1722075830.921310 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1104 submit DEBUG: Task 0 set to pending state with AppFuture: <AppFuture at 0x7f48709c8280 state=pending>
1722075830.921627 2024-07-27 18:23:50 MainProcess-1068150 Dependency-Launch_0-139949092083456 parsl.dataflow.memoization:222 check_memo DEBUG: Task 0 will not be memoized
1722075830.921741 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1016 submit DEBUG: Task 1 will be sent to executor threads
1722075830.922770 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:818 _add_output_deps DEBUG: Adding output dependencies
1722075830.922849 2024-07-27 18:23:50 MainProcess-1068150 Dependency-Launch_0-139949092083456 parsl.dataflow.dflow:776 launch_task INFO: Parsl task 0 try 0 launched on executor threads
1722075830.922901 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1067 submit DEBUG: Added output dependencies
1722075830.922987 2024-07-27 18:23:50 MainProcess-1068150 Dependency-Launch_0-139949092083456 parsl.dataflow.dflow:1476 log_std_stream INFO: Standard out for task 0 will not be redirected.
1722075830.923058 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1080 submit DEBUG: Gathering dependencies
1722075830.923140 2024-07-27 18:23:50 MainProcess-1068150 Dependency-Launch_0-139949092083456 parsl.dataflow.dflow:1476 log_std_stream INFO: Standard error for task 0 will not be redirected.
1722075830.923265 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1083 submit DEBUG: Gathered dependencies
1722075830.923348 2024-07-27 18:23:50 MainProcess-1068150 Dependency-Launch_0-139949092083456 parsl.process_loggers:27 wrapped DEBUG: Normal ending for _launch_if_ready_async on thread Dependency-Launch_0
1722075830.923419 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1098 submit INFO: Task 1 submitted for App preprocess_data, not waiting on any dependency
1722075830.923562 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1104 submit DEBUG: Task 1 set to pending state with AppFuture: <AppFuture at 0x7f487079cf40 state=pending>
1722075830.923959 2024-07-27 18:23:50 MainProcess-1068150 Dependency-Launch_0-139949092083456 parsl.dataflow.memoization:222 check_memo DEBUG: Task 1 will not be memoized
1722075830.924658 2024-07-27 18:23:50 MainProcess-1068150 Dependency-Launch_0-139949092083456 parsl.dataflow.dflow:776 launch_task INFO: Parsl task 1 try 0 launched on executor threads
1722075830.924738 2024-07-27 18:23:50 MainProcess-1068150 Dependency-Launch_0-139949092083456 parsl.dataflow.dflow:1478 log_std_stream INFO: Standard out for task 1 will be redirected to preprocess_data.out
1722075830.924981 2024-07-27 18:23:50 MainProcess-1068150 Dependency-Launch_0-139949092083456 parsl.dataflow.dflow:1478 log_std_stream INFO: Standard error for task 1 will be redirected to preprocess_data.err
1722075830.925080 2024-07-27 18:23:50 MainProcess-1068150 Dependency-Launch_0-139949092083456 parsl.process_loggers:27 wrapped DEBUG: Normal ending for _launch_if_ready_async on thread Dependency-Launch_0
1722075830.927815 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1016 submit DEBUG: Task 2 will be sent to executor _parsl_internal
1722075830.927925 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:818 _add_output_deps DEBUG: Adding output dependencies
1722075830.927985 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1067 submit DEBUG: Added output dependencies
1722075830.928036 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1080 submit DEBUG: Gathering dependencies
1722075830.928185 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1083 submit DEBUG: Gathered dependencies
1722075830.928247 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1098 submit INFO: Task 2 submitted for App deferred_getattr, waiting on task 1
1722075830.928312 2024-07-27 18:23:50 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1104 submit DEBUG: Task 2 set to pending state with AppFuture: <AppFuture at 0x7f487079c6a0 state=pending>
1722075830.928500 2024-07-27 18:23:50 MainProcess-1068150 Dependency-Launch_0-139949092083456 parsl.dataflow.dflow:664 _launch_if_ready_async DEBUG: Task 2 has outstanding dependencies, so launch_if_ready skipping
1722075830.928584 2024-07-27 18:23:50 MainProcess-1068150 Dependency-Launch_0-139949092083456 parsl.process_loggers:27 wrapped DEBUG: Normal ending for _launch_if_ready_async on thread Dependency-Launch_0
1722075835.918094 2024-07-27 18:23:55 MainProcess-1068150 JobStatusPoller-Timer-Thread-139949102745008-139949100476160 parsl.jobs.strategy:184 _general_strategy DEBUG: general strategy starting with strategy_type simple for 0 executors
1722075835.918342 2024-07-27 18:23:55 MainProcess-1068150 JobStatusPoller-Timer-Thread-139949102745008-139949100476160 parsl.process_loggers:27 wrapped DEBUG: Normal ending for _general_strategy on thread JobStatusPoller-Timer-Thread-139949102745008
1722075836.371846 2024-07-27 18:23:56 MainProcess-1068150 ThreadPoolExecutor-0_1-139949075298048 parsl.app.errors:113 reraise DEBUG: Reraising exception of type <class 'parsl.app.errors.BashExitFailure'>
1722075836.372409 2024-07-27 18:23:56 MainProcess-1068150 ThreadPoolExecutor-0_1-139949075298048 parsl.dataflow.dflow:351 handle_exec_update INFO: Task 1 try 0 failed with exception of type BashExitFailure
1722075836.372556 2024-07-27 18:23:56 MainProcess-1068150 ThreadPoolExecutor-0_1-139949075298048 parsl.dataflow.dflow:397 handle_exec_update ERROR: Task 1 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 348, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 618, in _unwrap_remote_exception_wrapper
    result.reraise()
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/errors.py", line 117, in reraise
    raise v
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/errors.py", line 141, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/bash.py", line 94, in remote_side_bash_executor
    raise pe.BashExitFailure(func_name, proc.returncode)
parsl.app.errors.BashExitFailure: bash_app preprocess_data failed with unix exit code 1
1722075836.373382 2024-07-27 18:23:56 MainProcess-1068150 ThreadPoolExecutor-0_1-139949075298048 concurrent.futures:332 _invoke_callbacks ERROR: exception calling callback for <AppFuture at 0x7f487079cf40 state=finished raised BashExitFailure>
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 348, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 618, in _unwrap_remote_exception_wrapper
    result.reraise()
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/errors.py", line 117, in reraise
    raise v
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/errors.py", line 141, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/bash.py", line 94, in remote_side_bash_executor
    raise pe.BashExitFailure(func_name, proc.returncode)
parsl.app.errors.BashExitFailure: bash_app preprocess_data failed with unix exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/concurrent/futures/_base.py", line 330, in _invoke_callbacks
    callback(self)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 1123, in callback_adapter
    self.launch_if_ready(task_record)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 646, in launch_if_ready
    self.dependency_launch_pool.submit(self._launch_if_ready_async, task_record)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
1722075836.374430 2024-07-27 18:23:56 MainProcess-1068150 ThreadPoolExecutor-0_1-139949075298048 parsl.dataflow.dflow:1478 log_std_stream INFO: Standard out for task 1 will be redirected to preprocess_data.out
1722075836.374532 2024-07-27 18:23:56 MainProcess-1068150 ThreadPoolExecutor-0_1-139949075298048 parsl.dataflow.dflow:1478 log_std_stream INFO: Standard error for task 1 will be redirected to preprocess_data.err
1722075836.984536 2024-07-27 18:23:56 MainProcess-1068150 MainThread-139949163136832 parsl.dataflow.dflow:1206 atexit_cleanup WARNING: Python is exiting with a DFK still running. You should call parsl.dfk().cleanup() before exiting to release any resources
